name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: GoLint
        run: |
          go env
          go install golang.org/x/lint/golint

      - name: Build
        run: make build

      - name: Test
        run: make test